### ISSUE TITLE
Milestone drag-and-drop not working in timeline

### ISSUE THREAD

**Issue by stevejburge** [upstreamplugin/UpStream-Project-Timeline#56]
We're having problems with the Milestones when dragging-and-dropping in the timeline

Customer video:
https://app.box.com/s/j3c8kvmqt6ql2xggmyrl3l3dwk6y1igi

**Comment by sergeidevstar001** [comment]
Problem : it used Math.round() on UpStream-Project-Timeline / assets / js / jquery.fn.gantt.js : Line 550
Solution : So it need to add one day more.

**Comment by sergeidevstar001** [comment]
Fixed :)
